- hosts: dev
  become: yes
  remote_user: ansible
  tasks:

    - name: Install Java(OpenJDK)
      yum:
        name: java
        state: latest

    - name: Add group called tomcat
      group:
        name: tomcat
        state: present

    - name: Add tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/bash

    - name: download tomcat8
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.32/bin/apache-tomcat-8.0.32.tar.gz
        dest: /opt

    - name: Uncompress Tomcat8
      unarchive:
        src: /opt/apache-tomcat-8.0.32.tar.gz
        dest: /opt
        remote_src: yes

    - name: Change file ownership, group and permission
      file:
        path: /opt/apache-tomcat-8.0.32
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory

    - name: Make tomcat symbolic link
      file:
        src: /opt/apache-tomcat-8.0.32
        dest: /opt/tomcat8
        owner: tomcat
        group: tomcat
        state: link

    - name: Make tomcat.service
      file:
        path: /etc/systemd/system/tomcat.service
        state: touch

    - name: Edit tomcat.service
      blockinfile:
        dest: /etc/systemd/system/tomcat.service
        insertafter:
        block: |
          [Unit]
          Description = Apache Tomcat 8
          After = syslog.target network.target
          [Service]
          User = tomcat
          Group = tomcat
          Type = oneshot
          PIDFile = /opt/apache-tomcat-8.0.32/tomcat.pid
          RemainAfterExit = yes
          ExecStart = /opt/apache-tomcat-8.0.32/bin/startup.sh
          ExecStop = /opt/apache-tomcat-8.0.32/bin/shutdown.sh
          ExecReStart = /opt/apache-tomcat-8.0.32/bin/shutdown.sh;/opt/apache-tomcat-8.0.32/bin/startup.sh
          [Install]
          WantedBy = multi-user.target

    - name: Change permissions of tomcat.service to 0755
      file:
        path: /etc/systemd/system/tomcat.service
        mode: 0755

    - name: Edit tomcat-users.xml file
      blockinfile:
        dest: /opt/apache-tomcat-8.0.32/conf/tomcat-users.xml
        insertafter: -->
        block: |
          <role rolename = "admin-gui" />
          <role rolename = "manager-gui" />
          <user username = "samakpan" password = "aniekan" roles = "admin-gui, manager-gui" />

    - name: Start tomcat
      systemd:
        name: tomcat.service
        state: started
        daemon_reload: yes
        enabled: yes

    - name: Download Jenkins
      get_url:
        url: https://get.jenkins.io/war-stable/2.249.2/jenkins.war
        dest: /opt/apache-tomcat-8.0.32/webapps

    - name: Download Epel 7
      get_url:
        url: http://rpmfind.net/linux/epel/7/x86_64/Packages/e/epel-release-7-12.noarch.rpm
        dest: /home

    - name: Install Git
      yum:
        name: git
        state: latest

    - name: Install Yum-Utils
      yum:
        name: yum-utils
        state: latest

    - name: Install Ansible
      yum:
        name: ansible
        state: latest

    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip
        dest: /home

    - name: Unzip Terraform
      unarchive:
        src: /home/terraform_0.13.4_linux_amd64.zip
        dest: /home
        remote_src: yes

    - name: Make Packer Directory
      file:
        path: /home/packer
        state: directory

    - name: Download Packer
      get_url:
        url: https://releases.hashicorp.com/packer/1.6.4/packer_1.6.4_linux_amd64.zip
        dest: /home/packer

    - name: Unzip Packer
      unarchive:
        src: /home/packer/packer_1.6.4_linux_amd64.zip
        dest: /home/packer
        remote_src: yes


